# Generated by Django 5.0 on 2023-12-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64)),
                ('order_name', models.CharField(max_length=64)),
                ('order_date', models.DateField()),
                ('order_quantity', models.IntegerField()),
            ],
        ),
    ]
